#!/bin/bash
# ============================================================================
# FOUNDRY — Multi-Agent Build Pipeline
# ============================================================================
# Takes a project spec folder → runs 6 focused agents in sequence →
# pauses for operator approval → deploys to GitHub + Vercel.
#
# Usage:
#   ./build-project.sh <project-id> [--resume-from <agent>] [--deploy]
#
# Examples:
#   ./build-project.sh demoseed               # Full pipeline (stops before deploy)
#   ./build-project.sh demoseed --resume-from qa  # Resume from QA agent
#   ./build-project.sh demoseed --deploy       # Run deployer only (after approval)
#
# Pipeline:
#   Planner → Builder → QA → Designer → Optimizer → [PAUSE] → Deployer
#
# Prerequisites:
#   - claude CLI (Claude Code) installed and authenticated
#   - gh CLI installed and authenticated
#   - vercel CLI installed and authenticated
#   - jq installed (brew install jq)
#   - Node.js installed
#
# Directory structure expected:
#   ~/Code/exploratory/
#   ├── foundry/     ← this script lives here
#   │   ├── build-project.sh
#   │   ├── projects.json
#   │   ├── agents/             ← agent definitions
#   │   │   ├── MASTER-ORCHESTRATOR.md
#   │   │   ├── planner.md
#   │   │   ├── builder.md
#   │   │   ├── qa.md
#   │   │   ├── designer.md
#   │   │   ├── optimizer.md
#   │   │   └── deployer.md
#   │   └── index.html
#   ├── <project-id>/           ← spec folder + built project
#   │   ├── *-SPEC.md
#   │   ├── CLAUDE-CODE-PROMPT.md
#   │   └── plan/               ← generated by Planner agent
#   └── ...
# ============================================================================

set -e

# Allow nested claude invocations (CLAUDECODE blocks them when run inside Claude Code)
unset CLAUDECODE

# Ensure Homebrew tools (flock, timeout) are in PATH for cron
export PATH="/opt/homebrew/bin:$PATH"

# ── CONFIG ──────────────────────────────────────────────────────────────────
ROOT_DIR="$HOME/Code/exploratory"
FACTORY_DIR="$ROOT_DIR/foundry"
AGENTS_DIR="$FACTORY_DIR/agents"
PROJECTS_JSON="$FACTORY_DIR/projects.json"
LOG_DIR="$FACTORY_DIR/logs"
STATE_DIR="$FACTORY_DIR/state"

# Max time (seconds) a single agent can run before we kill it
AGENT_TIMEOUT=2700  # 45 minutes

# Max retries per agent
MAX_RETRIES=2

# Lock file for projects.json concurrent writes
LOCK_FILE="$FACTORY_DIR/.projects.lock"

source "$FACTORY_DIR/lib/state.sh"

# ── COLORS ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'

# ── HELPERS ─────────────────────────────────────────────────────────────────
log()   { echo -e "${BLUE}[factory]${NC} $1"; }
ok()    { echo -e "${GREEN}[  ✓  ]${NC} $1"; }
warn()  { echo -e "${YELLOW}[ ⚠️  ]${NC} $1"; }
fail()  { echo -e "${RED}[  ✗  ]${NC} $1"; exit 1; }
step()  { echo -e "\n${PURPLE}${BOLD}── $1 ──${NC}\n"; }
agent() { echo -e "${CYAN}[agent]${NC} $1"; }

# flock-safe projects.json update
# Usage: write_projects_json <jq-filter>
write_projects_json() {
  local filter="$1"
  (
    flock -x 200
    jq "$filter" "$PROJECTS_JSON" > "${PROJECTS_JSON}.tmp" && mv "${PROJECTS_JSON}.tmp" "$PROJECTS_JSON"
  ) 200>"$LOCK_FILE"
}

# ── PARSE ARGS ──────────────────────────────────────────────────────────────
PROJECT_ID="${1:?Usage: ./build-project.sh <project-id> [--resume-from <agent>] [--deploy]}"
shift

RESUME_FROM=""
DEPLOY_ONLY=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --resume-from)
      RESUME_FROM="$2"
      shift 2
      ;;
    --deploy)
      DEPLOY_ONLY=true
      shift
      ;;
    *)
      warn "Unknown argument: $1"
      shift
      ;;
  esac
done

# ── VALIDATE PROJECT ───────────────────────────────────────────────────────
SPEC_DIR="$ROOT_DIR/$PROJECT_ID"
PROJECT_DIR="$ROOT_DIR/$PROJECT_ID"

if [ ! -d "$SPEC_DIR" ]; then
  fail "Spec directory not found: $SPEC_DIR"
fi

SPEC_FILE=$(find "$SPEC_DIR" -name "*SPEC.md" -maxdepth 1 | head -1)
PROMPT_FILE="$SPEC_DIR/CLAUDE-CODE-PROMPT.md"

if [ -z "$SPEC_FILE" ]; then
  fail "No *SPEC.md file found in $SPEC_DIR"
fi

if [ ! -f "$PROMPT_FILE" ]; then
  fail "CLAUDE-CODE-PROMPT.md not found in $SPEC_DIR"
fi

# Create directories
mkdir -p "$LOG_DIR" "$STATE_DIR" "$PROJECT_DIR/plan"

LOG_FILE="$LOG_DIR/${PROJECT_ID}-$(date +%Y%m%d-%H%M%S).log"
STATE_FILE="$STATE_DIR/${PROJECT_ID}-state.json"

# ── READ PROJECT INFO ───────────────────────────────────────────────────────
PROJECT_NAME=$(jq -r ".projects[] | select(.id == \"$PROJECT_ID\") | .name" "$PROJECTS_JSON" 2>/dev/null || echo "$PROJECT_ID")
SPEC_BASENAME=$(basename "$SPEC_FILE")
BUILD_ISSUE_ID=$(get_project_field "$PROJECT_ID" ".linear.build_issue_id // empty")

echo -e "\n${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║     FOUNDRY — Multi-Agent Build Pipeline     ║${NC}"
echo -e "${BOLD}╠══════════════════════════════════════════════════════════╣${NC}"
echo -e "${BOLD}║${NC}  Project:  ${GREEN}$PROJECT_NAME${NC}"
echo -e "${BOLD}║${NC}  Spec:     ${BLUE}$SPEC_BASENAME${NC}"
echo -e "${BOLD}║${NC}  Dir:      ${BLUE}$PROJECT_DIR${NC}"
echo -e "${BOLD}║${NC}  Log:      ${BLUE}$LOG_FILE${NC}"
if [ -n "$RESUME_FROM" ]; then
  echo -e "${BOLD}║${NC}  Resume:   ${YELLOW}from $RESUME_FROM${NC}"
fi
if [ "$DEPLOY_ONLY" = true ]; then
  echo -e "${BOLD}║${NC}  Mode:     ${GREEN}DEPLOY ONLY${NC}"
fi
echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${NC}\n"

# ── STATE MANAGEMENT ────────────────────────────────────────────────────────
init_state() {
  cat > "$STATE_FILE" << EOF
{
  "project_id": "$PROJECT_ID",
  "current_step": "planner",
  "status": "in_progress",
  "started_at": "$(date -u +%Y-%m-%dT%H:%M:%S)",
  "steps": {
    "planner":   { "status": "pending", "duration": "", "notes": "" },
    "builder":   { "status": "pending", "duration": "", "notes": "" },
    "qa":        { "status": "pending", "duration": "", "notes": "" },
    "designer":  { "status": "pending", "duration": "", "notes": "" },
    "optimizer": { "status": "pending", "duration": "", "notes": "" },
    "deployer":  { "status": "pending", "duration": "", "notes": "" }
  },
  "errors": [],
  "paused": false,
  "pause_reason": "",
  "agent_timings": {}
}
EOF
}

update_step() {
  local step_name="$1"
  local status="$2"
  local duration="$3"
  local notes="$4"
  jq "(.steps.\"$step_name\") = {\"status\": \"$status\", \"duration\": \"$duration\", \"notes\": \"$notes\"} | .current_step = \"$step_name\"" "$STATE_FILE" > "${STATE_FILE}.tmp" && mv "${STATE_FILE}.tmp" "$STATE_FILE"
}

pause_project() {
  local reason="$1"
  jq ".paused = true | .pause_reason = \"$reason\" | .status = \"paused\"" "$STATE_FILE" > "${STATE_FILE}.tmp" && mv "${STATE_FILE}.tmp" "$STATE_FILE"
}

# ── AGENT MODEL MAP ─────────────────────────────────────────────────────────
# Heavy agents (create code, design) get Opus; lightweight agents get Sonnet
agent_model() {
  case "$1" in
    builder|designer|optimizer|deployer) echo "claude-opus-4-6" ;;
    *)                                   echo "claude-sonnet-4-6" ;;
  esac
}

# ── AGENT RUNNER ────────────────────────────────────────────────────────────
# Runs a single agent via claude -p with the agent's prompt + project context
run_agent() {
  local agent_name="$1"
  local agent_file="$AGENTS_DIR/${agent_name}.md"
  local start_time=$(date +%s)

  if [ ! -f "$agent_file" ]; then
    fail "Agent definition not found: $agent_file"
  fi

  agent "Starting $agent_name agent..."
  update_step "$agent_name" "in_progress" "" ""

  # Read agent definition
  local agent_prompt
  agent_prompt=$(cat "$agent_file")

  # Build the context-aware prompt
  local full_prompt="You are the $agent_name agent in the Foundry pipeline.

PROJECT CONTEXT:
- Project ID: $PROJECT_ID
- Project Name: $PROJECT_NAME
- Project Directory: $PROJECT_DIR
- Spec File: $SPEC_BASENAME
- Factory Directory: $FACTORY_DIR

YOUR AGENT DEFINITION:
$agent_prompt

INSTRUCTIONS:
You are in the directory: $PROJECT_DIR
Execute your role as defined above. Be thorough but efficient.
When done, make sure npm run build passes (if applicable to your role)."

  cd "$PROJECT_DIR"

  # Run Claude Code with timeout
  local attempt=1
  local success=false

  while [ $attempt -le $MAX_RETRIES ] && [ "$success" = false ]; do
    agent "Attempt $attempt/$MAX_RETRIES for $agent_name..."

    unset CLAUDECODE
    timeout "$AGENT_TIMEOUT" claude \
      --dangerously-skip-permissions \
      --model "$(agent_model "$agent_name")" \
      --add-dir "$PROJECT_DIR" \
      --add-dir "$FACTORY_DIR" \
      -p "$full_prompt" 2>&1 | tee -a "$LOG_FILE"
    local exit_code="${PIPESTATUS[0]}"

    if [ "$exit_code" -eq 0 ]; then
      success=true
    else
      if [ "$exit_code" -eq 124 ]; then
        warn "$agent_name agent timed out after ${AGENT_TIMEOUT}s (attempt $attempt)"
      else
        warn "$agent_name agent failed with exit code $exit_code (attempt $attempt)"
      fi
      attempt=$((attempt + 1))
    fi
  done

  local end_time=$(date +%s)
  local duration="$((end_time - start_time))s"

  if [ "$success" = true ]; then
    update_step "$agent_name" "complete" "$duration" ""
    ok "$agent_name agent complete (${duration})"
    return 0
  else
    update_step "$agent_name" "failed" "$duration" "Failed after $MAX_RETRIES attempts"
    warn "$agent_name agent failed after $MAX_RETRIES attempts"
    return 1
  fi
}

# ── PIPELINE DEFINITION ────────────────────────────────────────────────────
# Agents in execution order (deployer handled separately)
PIPELINE_AGENTS=("planner" "builder" "qa" "designer" "optimizer")

# ── HANDLE --deploy FLAG ────────────────────────────────────────────────────
if [ "$DEPLOY_ONLY" = true ]; then
  step "Deploy Mode: Running deployer agent only"

  # Verify build passes before deploying
  cd "$PROJECT_DIR"
  if ! npm run build 2>/dev/null; then
    fail "npm run build failed — cannot deploy. Fix the build first."
  fi

  run_agent "deployer" || fail "Deployer agent failed"
  ok "Deployment complete!"

  # Show final status
  echo -e "\n${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
  echo -e "${BOLD}║              DEPLOYMENT COMPLETE                         ║${NC}"
  echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${NC}\n"
  exit 0
fi

# ── UPDATE STATUS → building ──────────────────────────────────────────────
step "Step 0: Initialize build"
write_projects_json "(.projects[] | select(.id == \"$PROJECT_ID\") | .status) = \"building\""
emit_event "build_started" "project_id=$PROJECT_ID" "project_name=$PROJECT_NAME"
append_history "🔨" "BUILDING" "$PROJECT_NAME"
linear_update_state "$BUILD_ISSUE_ID" "In Progress" || true
LINEAR_PROJECT_ID=$(get_project_field "$PROJECT_ID" ".linear.project_id // empty")
linear_post_update "$LINEAR_PROJECT_ID" "🔨 **Build pipeline started**\n\nRunning 5 agents in sequence: Planner → Builder → QA → Designer → Optimizer" "onTrack" || true

# Initialize or load state
if [ -n "$RESUME_FROM" ]; then
  log "Resuming from $RESUME_FROM agent"
else
  init_state
fi
ok "Status updated to 'building'"

# ── RUN PIPELINE ────────────────────────────────────────────────────────────
SKIP_UNTIL="$RESUME_FROM"
PIPELINE_FAILED=false

for agent_name in "${PIPELINE_AGENTS[@]}"; do
  # Skip agents until we hit the resume point
  if [ -n "$SKIP_UNTIL" ]; then
    if [ "$agent_name" != "$SKIP_UNTIL" ]; then
      log "Skipping $agent_name (resuming from $SKIP_UNTIL)"
      continue
    else
      SKIP_UNTIL=""  # Found the resume point, start running
    fi
  fi

  step "Agent: $agent_name"

  _agent_start=$(date +%s)
  if ! run_agent "$agent_name"; then
    _agent_end=$(date +%s)
    _agent_dur=$((_agent_end - _agent_start))
    emit_event "agent_failed" "project_id=$PROJECT_ID" "agent=$agent_name"
    linear_update_state "$BUILD_ISSUE_ID" "In Review" || true
    linear_add_comment "$BUILD_ISSUE_ID" "⚠️ Paused: **$agent_name** failed after $MAX_RETRIES attempts (${_agent_dur}s)" || true
    PIPELINE_FAILED=true
    pause_project "$agent_name agent failed after $MAX_RETRIES attempts"
    warn "Pipeline paused at $agent_name"
    break
  fi
  _agent_end=$(date +%s)
  _agent_dur=$((_agent_end - _agent_start))
  emit_event "agent_complete" "project_id=$PROJECT_ID" "agent=$agent_name" "duration_secs=$_agent_dur"
  write_projects_json "(.projects[] | select(.id == \"$PROJECT_ID\") | .agent_timings.$agent_name) = $_agent_dur"
  linear_add_comment "$BUILD_ISSUE_ID" "✓ **$agent_name** complete (${_agent_dur}s)" || true
  case "$agent_name" in
    planner)   _agent_msg="✅ **Planner complete** (${_agent_dur}s) — architecture plan and file structure ready" ;;
    builder)   _agent_msg="✅ **Builder complete** (${_agent_dur}s) — full codebase generated" ;;
    qa)        _agent_msg="✅ **QA complete** (${_agent_dur}s) — tests passing, build verified" ;;
    designer)  _agent_msg="✅ **Designer complete** (${_agent_dur}s) — UI polished and refined" ;;
    optimizer) _agent_msg="✅ **Optimizer complete** (${_agent_dur}s) — performance tuned, final build clean" ;;
    *)         _agent_msg="✅ **${agent_name} complete** (${_agent_dur}s)" ;;
  esac
  linear_post_update "$LINEAR_PROJECT_ID" "$_agent_msg" "onTrack" || true

  # After Builder, verify build passes before continuing
  if [ "$agent_name" = "builder" ] || [ "$agent_name" = "qa" ]; then
    cd "$PROJECT_DIR"
    if [ -f "package.json" ]; then
      log "Verifying npm run build..."
      if ! npm run build 2>&1 | tail -5; then
        warn "Build failed after $agent_name — pausing pipeline"
        PIPELINE_FAILED=true
        pause_project "npm run build failed after $agent_name agent"
        break
      fi
      ok "Build verified after $agent_name"
    fi
  fi
done

# ── POST-PIPELINE ──────────────────────────────────────────────────────────
if [ "$PIPELINE_FAILED" = true ]; then
  # Update status to indicate it needs attention
  write_projects_json "(.projects[] | select(.id == \"$PROJECT_ID\") | .status) = \"paused\""
  emit_event "build_paused" "project_id=$PROJECT_ID" "agent=$agent_name" "reason=agent failed after retries"
  append_history "⏸" "PAUSED" "$PROJECT_NAME — paused at $agent_name"
  linear_post_update "$LINEAR_PROJECT_ID" "⚠️ **Build paused** at ${agent_name}\n\n**Reason:** ${agent_name} failed after ${MAX_RETRIES} attempts\n\n**To resume:** \`./build-project.sh ${PROJECT_ID} --resume-from ${agent_name}\`" "atRisk" || true

  echo -e "\n${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
  echo -e "${BOLD}║           PIPELINE PAUSED — NEEDS ATTENTION             ║${NC}"
  echo -e "${BOLD}╠══════════════════════════════════════════════════════════╣${NC}"
  echo -e "${BOLD}║${NC}  Project: ${GREEN}$PROJECT_NAME${NC}"
  echo -e "${BOLD}║${NC}  State:   ${BLUE}$STATE_FILE${NC}"
  echo -e "${BOLD}║${NC}  Log:     ${BLUE}$LOG_FILE${NC}"
  echo -e "${BOLD}║${NC}"
  echo -e "${BOLD}║${NC}  ${YELLOW}Review the state file and log, then either:${NC}"
  echo -e "${BOLD}║${NC}  ${YELLOW}  ./build-project.sh $PROJECT_ID --resume-from <agent>${NC}"
  echo -e "${BOLD}║${NC}  ${YELLOW}or fix the issue manually and re-run.${NC}"
  echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${NC}\n"
  exit 1
fi

# Final build gate — catches any breakage introduced by designer/optimizer
cd "$PROJECT_DIR"
if [ -f "package.json" ]; then
  log "Final build verification..."
  if ! npm run build 2>&1 | tail -10; then
    warn "Final build failed — pausing pipeline"
    write_projects_json "(.projects[] | select(.id == \"$PROJECT_ID\") | .status) = \"paused\""
    pause_project "npm run build failed after optimizer agent"
    echo -e "\n${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║           FINAL BUILD FAILED — NEEDS ATTENTION          ║${NC}"
    echo -e "${BOLD}╠══════════════════════════════════════════════════════════╣${NC}"
    echo -e "${BOLD}║${NC}  Project: ${GREEN}$PROJECT_NAME${NC}"
    echo -e "${BOLD}║${NC}  Log:     ${BLUE}$LOG_FILE${NC}"
    echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${NC}\n"
    exit 1
  fi
  ok "Final build verified"
fi

# Pipeline succeeded — update status to "built" and pause for deploy approval
write_projects_json "(.projects[] | select(.id == \"$PROJECT_ID\") | .status) = \"built\""
emit_event "build_complete" "project_id=$PROJECT_ID" "project_name=$PROJECT_NAME"
append_history "✅" "BUILT" "$PROJECT_NAME — all 5 agents passed"
update_step "deployer" "awaiting_approval" "" ""
linear_post_update "$LINEAR_PROJECT_ID" "🏗️ **Build complete** — all 5 agents passed\n\nAuto-deploying to GitHub + Vercel now..." "onTrack" || true

# Linear: Build → Done, create Deploy issue, link and assign to project
linear_update_state "$BUILD_ISSUE_ID" "Done" || true
_DEPLOY_ISSUE_ID=$(linear_create_issue "${PROJECT_NAME} — Deploy" \
  "Build complete. All 5 agents passed. Auto-deploying to GitHub + Vercel." \
  "Todo" "Deploy") || _DEPLOY_ISSUE_ID=""
linear_assign_to_project "$_DEPLOY_ISSUE_ID" "$LINEAR_PROJECT_ID" || true
if [ -n "${BUILD_ISSUE_ID:-}" ] && [ -n "${_DEPLOY_ISSUE_ID:-}" ]; then
  linear_link_issues "$BUILD_ISSUE_ID" "$_DEPLOY_ISSUE_ID" || true
fi
if [ -n "${_DEPLOY_ISSUE_ID:-}" ]; then
  write_projects_json "(.projects[] | select(.id == \"$PROJECT_ID\") | .linear.deploy_issue_id) = \"$_DEPLOY_ISSUE_ID\""
fi

echo -e "\n${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║           BUILD COMPLETE — AWAITING DEPLOY APPROVAL     ║${NC}"
echo -e "${BOLD}╠══════════════════════════════════════════════════════════╣${NC}"
echo -e "${BOLD}║${NC}  Project:  ${GREEN}$PROJECT_NAME${NC}"
echo -e "${BOLD}║${NC}  Status:   ${GREEN}built (all 5 agents passed)${NC}"
echo -e "${BOLD}║${NC}  Log:      ${BLUE}$LOG_FILE${NC}"
echo -e "${BOLD}║${NC}"
echo -e "${BOLD}║${NC}  ${YELLOW}To deploy, run:${NC}"
echo -e "${BOLD}║${NC}  ${CYAN}./build-project.sh $PROJECT_ID --deploy${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${NC}\n"
